### ISSUE TITLE
plot ZOP not working

### ISSUE THREAD

**Issue by CloudyOverhead** [groupeLIAMG/BhTomoPy#27]

**Comment by FelixGirard** [comment]
The function calculate_Vapp was asking for a second parameter called 'air'
`    def calculate_Vapp(self, mog, air): ...`
That paramater was not referenced in the function. Removing it to : 
`    def calculate_Vapp(self, mog): ...`
Cause the interface to show like this (with database.db, t0302 with airshots): 
![image](https://user-images.githubusercontent.com/7445146/29325884-5f0786d2-81b7-11e7-81bc-af5822b9ef21.png)
Is the additionnal parameter 'air' useless ?

**Comment by FelixGirard** [comment]
Useless since already in the Mog. Remove the air parameter
