### ISSUE TITLE
ray coverage not working

### ISSUE THREAD

**Issue by CloudyOverhead** [groupeLIAMG/BhTomoPy#28]

**Comment by FelixGirard** [comment]
Tried it and showed : 
![image](https://user-images.githubusercontent.com/7445146/29325983-b5b512ba-81b7-11e7-974b-35e1f5a48680.png)
More details needed on the bug to reproduce it correctly.

**Comment by FelixGirard** [comment]
Vertical line should not be there. Also, the entire coverage not working as supposed to. See the matlab version for the desired output
